apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dein-benutzername/my-dns-deployment.git'
    targetRevision: HEAD
    path: charts/coredns
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

